npmMinimalAgeGate: 4320

npmPreapprovedPackages:
  - '@payfit/*'
  - '@jetlang/*'
  - nx@*
  - '@nx/*'
  - '@tanstack/*'

npmRegistries:
  //registry.npmjs.org/:
    npmAuthToken: '${NPM_TOKEN:-}'
  //registry.yarnpkg.com/:
    npmAuthToken: '${NPM_TOKEN:-}'
